var gfc = require('./datasets/gfcmergednew.json')
var old = require('./datasets/convertcsv.json')
var n = require('./datasets/allmergednew.json')
var fs = require('fs')

ratingMap = {
    'Mixture' : false,
    'Several Times' : false,
    'Lies' : false,
    'Correct Attribution': true,
    'False': false,
    'Fake news' : false,
    'Needs Context' : false,
    'Falsehood': false,
    'Fals' : false,
    'Injustice' : false,
    'Unverified' : false,
    'misleading' : false,
    'Partly False' : false,
    'Out of context' : false,
    'FALSE': false,
    'True': true,
    'Wrong Country' : false,
    'Wrong' : false,
    'The war in Ukraine and sanctions introduced on Russia as a result of its invasion have disrupted the supply of various products, though it is not the only cause of supply issues.' : false,
    'Fake.' : false,
    'Thematic content is missing' : false,
    'Missing context.': false,
    'deceitful': false,
    'incomplete map': false,
    'Unproven': false,
    'false': false,
    'Missing context': false,
    'Misleading': false,
    'Parody': false,
    'Altered photo': false,
    'False. The video shows actors making a Ukrainian TV series in 2020.': false,
    'The video appears to predate the Russian invasion of Ukraine, and there is no proof the soldiers are from two different forces. .': false,
    'Certain': true,
    'to lie': false,
    'Misinformation': false,
    'TRUE': true,
    'This clip is not from Ukraine. It has been manipulated, with the original footage being taken at a climate protest in Vienna.': false,
    'Manipulated': false,
    'Old Video': false,
    'mislead': false,
    'NO': false,
    'Fake News. It is multiple scenes edited together from episodes and video games': false,
    'Salah': false,
    'Missing Context': false,
    "In Putin's speech there are many inaccuracies if not outright lies, it is understandable that the Russian leader tells them to his citizens, that an Italian senator uncritically sells them to us citizens is serious.": false,
    'This appears to be accurate but lacks the context that many other countries taking refugees never required visas for Ukrainians, or have waived visa requirements.': true,
    'Falsehood. The vast majority of refugees are Ukrainians who are fleeing the war. Foreigners who stayed there also seek shelter, but they are not the majority.': false,
    'different context': false,
    'Altered': false,
    'Miscaptioned': false,
    'Out of Context': false,
    'Mostly False': false,
    'Pants on Fire': false,
    'Falsehood. The invasion is a violation of international law for which Russia is responsible. There is no evidence of an international conspiracy to lead to an invasion.': false,
    'True, but...': true,
    'Older Photos': false,
    'missing context': false,
    '2018 Report': false,
    'Authentic': true,
    'This was a rumour that appears to be untrue. Pornhub worked normally when other fact checkers used software to simulate a visit from Russia.': false,
    '2016 Photo': false,
    'MISLEADING': false,
    'decontextualized': false,
    'False.': false,
    'Pre-Invasion': false,
    '2021 Photo': false,
    'The footage is actually from May 2020, and shows preparations for a military parade near Moscow.': false,
    'Incorrect': false,
    'The video is a CGI animation of WW2 and was put online long before the 2022 invasion.': false,
    'FalseContext / False': false,
    'Some of these videos clearly do not depict the Russian invasion of Ukraine as they predate the invasion.': false,
    'False. It shows footage of a military parade rehearsal from May 2020.': false,
    'At least some of the videos do not show this.': false,
    'Distorts the Facts': false,
    'Although the nature of any armed conflict makes it impossible to obtain accurate statistics, there are good reasons to doubt this figure.': false,
    'Mostly True': true,
    'Misleading Material': false,
    'False Context': false,
    'False context': false,
    'Half true': true,
    'Altered media': false,
    'Mostly false': false,
    'The video is screengrab of a video game': false,
    'Misleading: Old video': false,
    'Repairs Made': false,
    'Incorrect. Strack-Zimmermann neither said nor implied that in the interview. She only explained requirements for the post of Secretary of Defense. The politician herself denies ever having spoken out in favor of the deployment of German soldiers in Ukraine.': false,
    'mistake': false,
    'really_false': false,
    'No War Plans': false,
    'No Blockade': false,
    'No Evacuation': false,
    'Not War Photos': false,
    'Faux': false,
    'Untrue' :false,
    'No Missile': false,
    'This image shows just one moment from the BBC’s coverage of the war in Ukraine. The full video shows Russian shelling and Ukrainian citizens fleeing, and this BBC report has been corroborated by other media outlets.': false,
    'The Chinese military has not entered Ukraine. The video shows a convoy in eastern Russia: vehicles on their way to the "Vostok" military exercise, which was held several thousand kilometers from the Ukrainian border in August.': false,
    'mistake. The group photo has nothing to do with the Russia-Ukraine War, but was taken during the 2014 Jordanian International Special Forces Contest.': false,
    'While all three companies have invested in Ukraine’s agricultural industry, there’s no evidence that President Zelenskyy sold large amounts of agricultural land to any of them.': false,
    'Please note that this statement is false. Elena Rybakina did start to cry during this press conference, but not for the reasons that are mentioned in this publication.': false,
    'Flip-flop': false,
    'to mislead': false,
    'Various Videos': false,
    'Misleading.': false,
    'Fake News. There is evidence of his identity': false,
    'Recycled List': false,
    'Anyone who is not covered by the EU Mass Influx Directive must, as before, face an asylum procedure. So not everyone can enter the EU under the guise of the Ukraine war, as is suggested. The man in the photo is not Ukrainian, but he fled from the Ukraine to Germany. He is said to have previously stayed in Ukraine as a football player.': false,
    'The collages for the supposed proof of the claim were manipulated. Scenes from several series episodes were put together.': false,
    'Image out of context': false,
    'Partly False and Misleading': false,
    'The claim is not substantiated.': false,
    'WRONG': false,
    "Between omissions and allusions, Marco Travaglio's editorial unfortunately propagates various inaccuracies, from the number of deaths in the Donbass, to the biochemical laboratories up to the exits of Biden's undersecretary, told out of context. That's not how journalism is done.": false,
    'Manipulated. The tweet is not from CNN but appears to have been created by a man named Majk Majkonski.': false,
    'The statement is incorrect.': false,
    'YES': true,
    'FAUX': false,
    '2014 Footage': false,
    'Edited image': false,
    'The video is real but not current. It was recorded on February 24th, but was not distributed until March 11th.': true,
    'distorted': false,
    'This is false. The footage is from a video game called Arma 3.': false,
    'Yuma Arizona': false,
    'Incorrect. The video was made in 2020 and during the shooting of the Ukrainian TV series "Contamin".': false,
    'Not Recent': false,
    'fake news. This is a derivative of the "Consent Denied or Algorithm" hoax, used to try to impose censorship on a sensitive topic': false,
    'Difficult to verify': false,
    'Altered image': false,
    'No Ghana Talk': false,
    'This only applies to one of the two scenes shown: the video of an explosion that was shown during a live broadcast of "Bild" on February 25, 2022 dates from 2015. The image of a badly damaged house, on the other hand, was actually taken on February 24. Recorded February 2022 in the eastern Ukrainian city of Chuhuiv.': false,
    'fake news. This is a photoshopped logo': false,
    'Misleading Content / Partly False': false,
    'The video is several years old and has nothing to do with Austria or the war in Ukraine. The subtitles are made up.': false,
    'Online in 2010': false,
    'Falsehood. The photo did not appear online until February 24, 2022. The author in an interview told about the circumstances of its making.': false,
    'Missing context. The Bild-TV report actually used two recordings that were several years old. The video has since been deleted and the incorrect images have been replaced with current images. The picture has publicly corrected its error.': false,
    'Warning: not all of them are real, they are often archival photos, recycled or misinterpreted for virality purposes.': false,
    'FalseContext/False': false,
    'Fake News. There are no situations such as to legitimize such measures, and the risk of creating the alleged disservice is large.': false,
    "It's actually a satellite launch from Cape Canaveral.": false,
    'Arma 3': false,
    'Unsubstantiated':false,
    'Experts Agree': true
  }

// r = new Set()
// gfc.forEach(ele => {
//     r.add(ele.claimReview[0].textualRating)
// })

// console.log(r)

// gfc.forEach(article => {
//     old.push({
//         no: old.length + 1,
//         claim: article.text,
//         truth_value: ratingMap[article.claimReview[0].textualRating],
//         source: article.claimant ? article.claimant : null
//     })
// })

// fs.writeFileSync('./datasets/allmergednew.json', JSON.stringify(old))

console.log(n.length)
